language: python

python:
  - 2.6
  - 2.7
  - pypy
  - 3.3

install:
  - pip install git+git://github.com/mitsuhiko/werkzeug.git#egg=Werkzeug
  - pip install git+git://github.com/mitsuhiko/flask.git#egg=Flask
  - pip install --editable .

script:
  - make test
  - sphinx-build -aEWb doctest docs docs/_build
