language: python

python:
  - 2.6
  - 2.7
  - pypy
  - 3.3

env:
  - REQUIREMENTS=lowest
  - REQUIREMENTS=release
  - REQUIREMENTS=devel

install:
  - pip install -r .travis-$REQUIREMENTS-requirements.txt
  - pip install --use-mirrors sphinx pyflakes
  - pip install --editable .

script:
  - make test
  - sphinx-build -aEWb doctest docs docs/_build
